export { default as Home } from "./Home/Home"
export { default as Search } from "./Search/Search"
export { default as Following } from "./Following/Following"
export { default as Profile } from "./Profile/Profile"
export { default as DetailProduct } from "./DetailProduct/DetailProduct"
